---
# task file for wildfly

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- include: configure.yml
  when: wildfly_manage_configuration

- include: users.yml

- include: ssl.yml
  when: wildfly_enable_ssl
